# Platform
TARGET_BOARD_PLATFORM := sm8475
TARGET_BOOTLOADER_BOARD_NAME := liuqin
BOARD_VENDOR := xiaomi

# Kernel
TARGET_KERNEL_ARCH := arm64
TARGET_KERNEL_HEADER_ARCH := arm64
BOARD_KERNEL_IMAGE_NAME := Image.gz
TARGET_PREBUILT_KERNEL := device/xiaomi/liuqin/kernel

# Boot image
BOARD_BOOTIMG_HEADER_VERSION := 3
BOARD_KERNEL_CMDLINE := console=ttyMSM0,115200n8 earlycon=msm_geni_serial,0x04C3D000 androidboot.console=ttyMSM0
BOARD_MKBOOTIMG_ARGS := --header_version $(BOARD_BOOTIMG_HEADER_VERSION)
BOARD_INCLUDE_DTB_IN_BOOTIMG := true

# Recovery
BOARD_USES_RECOVERY_AS_BOOT := true
BOARD_BUILD_SYSTEM_ROOT_IMAGE := false

# A/B
AB_OTA_UPDATER := true
BOARD_USES_METADATA_PARTITION := true

# Filesystem
BOARD_FLASH_BLOCK_SIZE := 131072 # (128 KB)

# System as root
BOARD_ROOT_EXTRA_FOLDERS := bluetooth dsp firmware persist
BOARD_SUPPRESS_SECURE_ERASE := true

BOARD_INCLUDE_RECOVERY_DTBO := true
BOARD_DTBOIMG_PARTITION_SIZE := 25165824 # Beispielwert (~24MB)
BOARD_KERNEL_SEPARATED_DTBO := true


#BOARD_AVB_ENABLE := true
#BOARD_AVB_MAKE_VBMETA_IMAGE_ARGS := --flag 2

BOARD_SUPER_PARTITION_BLOCK_DEVICES := system vendor product
BOARD_SUPER_PARTITION_METADATA_DEVICE := system
BOARD_SUPER_PARTITION_SIZE := 9126805504  # Beispielwert aus `super.img`
BOARD_BUILD_SUPER_IMAGE_BY_DEFAULT := true
BOARD_FLASH_SUPER_PARTITION := true
